name: my_enve
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8 # Specify the Python version you want, e.g., 3.8
  - pip
  - pip:
      - streamlit
      - instructor
      - python-dotenv
      - crewai
      - langchain-community
      - langchain
      - langchain-core
      - langchain-openai
